### ISSUE TITLE
release NoClassDefFoundError,debug is fine

### ISSUE THREAD

**Issue by LeonShannon** [Ekito/koin#1906]
**Describe the bug**
Launch in release mode, debug is fine
gradle 8.5 does not work, 8.3.2 does

Log
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/vgjump/jump/ui/main/MainConfigViewModel;
                                                                                        	at com.vgjump.jump.config.P0.q1(SourceFile:25)
                                                                                        	at com.vgjump.jump.config.P0.l(SourceFile:1)
                                                                                        	at com.vgjump.jump.config.M0.invoke(SourceFile:1)
                                                                                        	at org.koin.dsl.ModuleDSLKt.module(SourceFile:4)
                                                                                        	at org.koin.dsl.ModuleDSLKt.module$default(SourceFile:2)
                                                                                        	at com.vgjump.jump.config.P0.<clinit>(SourceFile:9)
                                                                                        	at com.vgjump.jump.App.J(SourceFile:14)
                                                                                        	at com.vgjump.jump.App.e(SourceFile:1)
                                                                                        	at com.vgjump.jump.b.invoke(SourceFile:1)
                                                                                        	at org.koin.core.context.GlobalContext.startKoin(SourceFile:8)
                                                                                        	at org.koin.core.context.DefaultContextExtKt.startKoin(SourceFile:2)
                                                                                        	at com.vgjump.jump.App.onCreate(SourceFile:73)
                                                                                        	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                        	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
                                                                                        	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
                                                                                        	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                        	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                        	at android.os.Looper.loop(Looper.java:319)
                                                                                        	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                        	at java.lang.reflect.Method.invoke(Native Method)
                                                                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                        Caused by: java.lang.ClassNotFoundException: com.vgjump.jump.ui.main.MainConfigViewModel
                                                                                        	at com.vgjump.jump.config.P0.q1(SourceFile:25) 
                                                                                        	at com.vgjump.jump.config.P0.l(SourceFile:1) 
                                                                                        	at com.vgjump.jump.config.M0.invoke(SourceFile:1) 
                                                                                        	at org.koin.dsl.ModuleDSLKt.module(SourceFile:4) 
                                                                                        	at org.koin.dsl.ModuleDSLKt.module$default(SourceFile:2) 
                                                                                        	at com.vgjump.jump.config.P0.<clinit>(SourceFile:9) 
                                                                                        	at com.vgjump.jump.App.J(SourceFile:14) 
                                                                                        	at com.vgjump.jump.App.e(SourceFile:1) 
                                                                                        	at com.vgjump.jump.b.invoke(SourceFile:1) 
                                                                                        	at org.koin.core.context.GlobalContext.startKoin(SourceFile:8) 
                                                                                        	at org.koin.core.context.DefaultContextExtKt.startKoin(SourceFile:2) 
                                                                                        	at com.vgjump.jump.App.onCreate(SourceFile:73) 
                                                                                        	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316) 
                                                                                        	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711) 
                                                                                        	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                        	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478) 
                                                                                        	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                        	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                        	at android.os.Looper.loop(Looper.java:319) 
                                                                                        	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                        	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                        	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                        	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) `

proguard
`-keep class org.koin.core.** { *; }
-keep interface org.koin.core.** { *; }
-keepclassmembers class * { public <init>(...); }
-keep class org.koin.** { *; }
-keep class org.koin.core.** { *; }
-keep class org.koin.dsl.** { *; }
`

**Koin module and version:**
koin-android = { module = "io.insert-koin:koin-android", version = "3.5.6" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version = "3.5.6" }

**Snippet or Sample project to help reproduce**
Add a snippet or even a small sample project to hel reproduce your case.

![image](https://github.com/InsertKoinIO/koin/assets/24221796/e9dfda88-9c2b-417c-95a4-7c48a462cbdd)

**Comment by MReP1** [comment]
Set Library module build.gradle isMinifyEnabled to false.

**Comment by HoseinSadonasl** [comment]
I have the same problem. Is there any news?

**Comment by gulomov** [comment]
I am facing this problem as well

**Comment by ShurikuS57** [comment]
+1

**Comment by sayah-y** [comment]
+1, I am trying to build a release build of my app. And I get the same error.
Please note that there is no error in debug.

**Comment by sayah-y** [comment]
It seems that it's not an issue with `Koin`.
Since 2 days, I tries to solve the same issue. I finally found the solution.

I have a structure with:
- androidApp
- iOSApp
- module1
- module2
- etc.

I only keep `isMinifyEnabled = true` in the androidApp.
In all modules, I set  `isMinifyEnabled = false`.
Now, everything works 👍 
I think, it's a gradle issue. I use gradle 8.7.

**Comment by arifaizin** [comment]
+1
