### ISSUE TITLE
Unable to run in old android versions

### ISSUE THREAD

**Issue by jlberrocal** [Ekito/koin#21]
I have been using this great library for some time, however i always tested in devices with SDK greater than 21 now i had to run it in a device with SDK 17 and i'm getting the following errors:
```
E/dalvikvm: Could not find class 'org.koin.android.module.AndroidModule$androidApplication$2', referenced from method org.koin.android.module.AndroidModule.<init>
```
and this is the final exception
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.ExceptionInInitializerError
                      at com.innoware.aeromedicion.MainApplication.onCreate(MainApplication.kt:24)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
                      at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:5041)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.NoClassDefFoundError: kotlin.jvm.internal.PropertyReference1Impl
                      at org.koin.android.module.AndroidModule.<clinit>(AndroidModule.kt)
                      at com.innoware.aeromedicion.MainApplication.onCreate(MainApplication.kt:24) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391) 
                      at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:5041) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by arnaudgiuliani** [comment]
Hello Did you rebuild entirely your project ? Did you check your app need multidex ?

We have several examples that run perfectly in 17
check the [Todo app](https://github.com/Ekito/android-architecture/tree/dev-todo-mvp-kotlin-koin)
for example

**Comment by jlberrocal** [comment]
Yes i rebuild my entire project with no positive results, multidex was enabled

with other DI library i had to change the Application class to MultiDexApplication and it worked, i don't know if the same fix apply for your library

**Comment by arnaudgiuliani** [comment]
Yes, try to change your supertype from Application to MultiDexApplication
