### ISSUE TITLE
org.koin.error.NoBeanDefFoundException: Multiple definition found for class

### ISSUE THREAD

**Issue by ChristopheCiambella** [Ekito/koin#39]
Hi,

I have an issue with Koin library, after following all initialization steps,  I used it for several weeks and worked like a charm, until now... 

I recently observed that one of my dependency is not longer injected, so I update my Koin version from 0.7.0-alpha-1 to 0.8.1-alpha-7. It didn't change anything.... 

It became even worse with this version, my application crash now and I receive this message : "Multiple definition found for class" . However my class is added once...

`
01-17 09:11:51.555 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.redesign.room.VDatabase, binds~(my.app.package.network.redesign.room.VDatabase)]
01-17 09:11:51.556 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.redesign.api.ProductService, binds~(my.app.package.network.redesign.api.ProductService)]
01-17 09:11:51.556 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.redesign.api.UserService, binds~(my.app.package.network.redesign.api.UserService)]
01-17 09:11:51.556 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.redesign.api.CommentService, binds~(my.app.package.network.redesign.api.CommentService)]
01-17 09:11:51.556 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.redesign.api.StaticService, binds~(my.app.package.network.redesign.api.StaticService)]
01-17 09:11:51.557 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.apis.VcProductApiService, binds~(my.app.package.network.apis.VcProductApiService)]
01-17 09:11:51.558 3695-3695/my.app.package I/KOIN: [init] declare : Bean[class=my.app.package.network.apis.VcNegotiationApiService, binds~(my.app.package.network.apis.VcNegotiationApiService)]
01-17 09:11:51.558 3695-3695/my.app.package I/KOIN: [init] loaded 7 definitions
01-17 09:11:51.558 3695-3695/my.app.package I/KOIN: [init] Load Android features
01-17 09:11:51.573 3695-3695/my.app.package I/KOIN: [Properties] no assets/koin.properties file to load
01-17 09:11:51.573 3695-3695/my.app.package I/KOIN: [init] ~ added Android application bean reference
01-17 09:11:53.613 3695-3695/my.app.package E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: my.app.package, PID: 3695
                                                                      org.koin.error.NoBeanDefFoundException: Multiple definition found for class class my.app.package.network.redesign.api.StaticService : 
                                                                       	[Bean[class=my.app.package.network.redesign.api.StaticService, binds~(my.app.package.network.redesign.api.StaticService)]]
                                                                       	[Bean[class=my.app.package.network.redesign.api.StaticService, binds~(my.app.package.network.redesign.api.StaticService)]]
                                                                          at org.koin.core.bean.BeanRegistry.searchAll(BeanRegistry.kt:87)
                                                                          at my.app.package.application.StaticContentProvider$$special$$inlined$inject$1$1.invoke(KoinContext.kt:48)
                                                                          at my.app.package.application.StaticContentProvider$$special$$inlined$inject$1$1.invoke(KoinContext.kt:20)
                                                                          at org.koin.KoinContext.resolveInstance(KoinContext.kt:65)
                                                                          at my.app.package.application.StaticContentProvider$$special$$inlined$inject$1.invoke(KoinComponent.kt:89)
                                                                          at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
                                                                          at my.app.package.application.StaticContentProvider.getService(StaticContentProvider.kt)
                                                                          at my.app.package.application.StaticContentProvider.access$getService$p(StaticContentProvider.kt:16)
                                                                          at my.app.package.application.StaticContentProvider$reloadData$1.doResume(StaticContentProvider.kt:36)
                                                                          at my.app.package.application.StaticContentProvider$reloadData$1.invoke(StaticContentProvider.kt)
                                                                          at my.app.package.application.StaticContentProvider$reloadData$1.invoke(StaticContentProvider.kt:16)
                                                                          at my.app.package.network.utils.RxExtensionKt$start$2.doResume(RxExtension.kt:24)
                                                                          at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
                                                                          at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:123)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by arnaudgiuliani** [comment]
Hello,

I see the problem. I tried to raise up multiple definition detection. Then if you can have a bean declared like
`provide { something type of StaticService} bind StaticService ::class`

To unblock your situation for now, try to declare components :
`provide { something } bind StaticService::class `
or
`provide { something as StaticService}``

This page can bring more help : http://insert-koin.io/docs/1.0/reference/koin-dsl/#binding-additional-types

I will make a fix, because bean reference lookup shows up the same bean definition.

**Comment by arnaudgiuliani** [comment]
Take a look on `0.8.1-alpha-8`

**Comment by ChristopheCiambella** [comment]
Thanks you ! This version correct my problem :)

**Comment by arnaudgiuliani** [comment]
Nice 👍
