### ISSUE TITLE
App crashes with VerifyError on launch

### ISSUE THREAD

**Issue by derTuca** [Ekito/koin#57]
Hi. First of all, nice work on Koin, it's such an awesome DI tool! I have a problem since upgrading from 0.8.0 to 0.8.2 with an Android app. The app crashes at startup with the following stack:

> java.lang.VerifyError: Verifier rejected class org.koin.core.property.PropertyRegistry: void org.koin.core.property.PropertyRegistry.deleteAll(java.lang.String[]) failed to verify: void org.koin.core.property.PropertyRegistry.deleteAll(java.lang.String[]): [0x10] register v4 has type Reference: java.lang.Object but expected Precise Reference: java.lang.String (declaration of 'org.koin.core.property.PropertyRegistry' appears in /data/app/com.theantimony.antimony-1/split_lib_directories_apk.apk:classes2.dex)
        at org.koin.Koin.<init>(Koin.kt:21)
        at org.koin.standalone.StandAloneContext.startKoin(StandAloneContext.kt:33)
        at org.koin.standalone.StandAloneContext.startKoin$default(StandAloneContext.kt:24)
        at org.koin.android.ext.android.AndroidExtKt.startKoin(AndroidExt.kt:27)
        at org.koin.android.ext.android.AndroidExtKt.startKoin$default(AndroidExt.kt:25)
        at com.theantimony.antimony.AntimonyApplication.onCreate(AntimonyApplication.kt:11)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5970)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

I have tried using Rebuild Project and deleting the build folder manually, and now the same thing happens after downgrading to 0.8.0 as well. Is this a knows issue? Thank you.

**Comment by arnaudgiuliani** [comment]
Hello,

seems to be a Kotlin compile error. Did you made a `gradle clean`. Or try to delete your .gradles ./build and .idea (or .iml) files.

**Comment by derTuca** [comment]
A clean didn't work, but it seems to be caused by the latest Android Studio alpha at the time of writing this message (3.2 alpha 3). Downgrading fixed the issue.

**Comment by arnaudgiuliani** [comment]
Ok cool.
