### ISSUE TITLE
ViewModel with interface

### ISSUE THREAD

**Issue by Shakezulla57** [Ekito/koin#69]
I'm not sure how to setup my module with this example below.

I have a `ViewModel`
```
class MyViewModel(private val interactor: Interactor) :
    ViewModel(), SomeInterface<SomeType1, SomeType2> {
.....
}
```

And I have a module
```
val myModule = applicationContext {
    viewModel { MyViewModel(get()) }
    bean { Interactor(get()) }
}
```

In my `activity` I have `val viewModel = getViewModel<MyViewModel>()`

When the activity starts it crashes because the `ViewModel` wasn't injected. I'm assuming it has something to do with my `interface` because everything worked fine until I added that. How would I go about resolving my `ViewModel` so I can inject it?

**Comment by fredy-mederos** [comment]
Change `val viewModel = getViewModel<MyViewModel>()` for `val viewModel by viewModel<MyViewModel>()` to inject the `ViewModel`

**Comment by Shakezulla57** [comment]
Thanks for the feedback. That leads me into this error.

```
Caused by: org.koin.error.BeanInstanceCreationException: Can't create bean Factory[class=com.my.presentation.MyViewModel, binds~(android.arch.lifecycle.ViewModel)] due to error :
    	java.lang.NullPointerException: composer is null
        at org.koin.core.instance.InstanceFactory.createInstance(InstanceFactory.kt:62)
        at org.koin.core.instance.InstanceFactory.retrieveInstance(InstanceFactory.kt:22)
        at org.koin.KoinContext.resolveInstance(KoinContext.kt:86)
        at org.koin.android.architecture.ext.KoinExtKt.getWithDefinitions(KoinExt.kt:48)
        at org.koin.android.architecture.ext.KoinExtKt.getByTypeName(KoinExt.kt:28)
        at org.koin.android.architecture.ext.KoinExtKt.get(KoinExt.kt:57)
        at org.koin.android.architecture.ext.KoinFactory.create(KoinFactory.kt:31)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:133)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:101)
        at org.koin.android.architecture.ext.LifecycleOwnerExtKt.getViewModelByClass(LifecycleOwnerExt.kt:81)
        at org.koin.android.architecture.ext.LifecycleOwnerExtKt$viewModelByClass$1.invoke(LifecycleOwnerExt.kt:36)
        at org.koin.android.architecture.ext.LifecycleOwnerExtKt$viewModelByClass$1.invoke(Unknown Source:0)
        at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
        at com.my.presentation.MyActivity.getViewModel(MyActivity.kt:0)
        at com.my.presentation.MyActivity.bind(MyActivity.kt:32)
        at com.my.presentation.MyActivity.onCreate(MyActivity.kt:25)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
```

**Comment by Shakezulla57** [comment]
Just to test I went back and am providing the `ViewModel` the "normal" way and it looks like its my own error in the view model itself. I'll update when I have more details.

**Comment by Shakezulla57** [comment]
`val viewModel by viewModel<MyViewModel>` works. I had some runtime issues with my `ViewModel` which were hard to tell from the stacktrace from Koin internals, but were obvious once I stopped injecting it with Koin.

**Comment by arnaudgiuliani** [comment]
Ok, no problem with Koin then?

**Comment by arnaudgiuliani** [comment]
I close the issue. reopen it if needed

**Comment by Shakezulla57** [comment]
No, no problem with Koin. The only thing is that the stack trace gets a bit eaten by the way Koin throws the exception

**Comment by arnaudgiuliani** [comment]
Sure

**Comment by caleb-allen** [comment]
#76 should expose the entire stack trace
